rssi:
  useChecksum: True
  maxOutstandingSegments: 8
  maxSegmentSize: 1400
  retransmissionTimeout_s: .5
  cumAckTimeout_s: .2
  nullTimeout_s: 3
  maxRetransmissions: 15
  maxCumAcks: 2
  minusLog10timeoutUnit: 3
